name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push
    runs-on: self-hosted
    environment: venv

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        id: vars
        run: |
          echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Export environment variables from secrets
        run: |
          echo "NTFY_BASE_URL=${{ secrets.NTFY_BASE_URL }}" > .env

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/qtor-fb-compressor:${TAG} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/qtor-fb-compressor:${TAG}

      - name: Print Image Info
        run: |
          echo "Image pushed: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/qtor-fb-compressor:${TAG}"

